language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get -y install gcc
  - sudo apt-get -y install clang

script:
  - mkdir build
  - cd build
  - cmake ../
  - make